project:
  type: website
  preview:
    host: 0.0.0.0
    port: 4210 # match devcontainer.json forwarded port
    browser: false # Optional: automatically open a browser
    navigate: false # Optional: automatically navigate the browser

website:
  title: "Victor Yuan"
  site-url: https://victoryuan.com
  description: "Victor's website"
  google-analytics: G-ZLSXEBDXV5
  navbar:
    search: true
    right:
      - href: projects
        text: Projects
      - href: posts
        text: Posts
      - icon: rss
        href: posts/index.xml
    tools:
      - icon: github
        href: https://www.github.com/wvictor14
      - icon: linkedin
        href: https://www.linkedin.com/in/victor2wy/
      - icon: envelope
        href: emailto:victor.2wy@gmail.com
  body-footer: |
    <script data-goatcounter="https://victor2wy.goatcounter.com/count"
        async src="//gc.zgo.at/count.js"></script>

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

execute:
  freeze: true